In [119]:
import pandas as pd
import numpy as np

In [120]:
recipe=pd.read_csv('Reciepe.csv')
reviews=pd.read_csv('reviews.csv')

In [121]:
type(reviews)

pandas.core.frame.DataFrame

In [122]:
md=recipe.merge(reviews,on='Recipe_Id')

In [123]:
type(md)

pandas.core.frame.DataFrame

In [124]:
type(recipe)

pandas.core.frame.DataFrame

In [125]:
md.head()

Name  Recipe_Id  \
0             Raw Banana Fry          1   
1                    Payasam          2   
2            Soy Dal Paratha          3   
3         Aloo Palak Paratha          4   
4  Chettinad Chicken Biryani          5   

                                   Ingredients  Calories  \
0                                       Banana       400   
1      Vermicelli  jaggery   ghee  cocunutmilk       500   
2             Flour  soyachunks  ghee  mongdal       460   
3         Flour  ghee  potato  spinach  cheese       350   
4  Chicken  tomatoes  yogurt  tomatoes  onions       250   

                Food type Veg/nonveg  Rating  \
0                 Snacks        Veg      4.0   
1               Desserts        Veg      5.0   
2   Starters  MainCourse        Veg      3.0   
3   Starters  MainCourse        Veg      5.0   
4             MainCourse     Nonveg      5.0   

                                    Review  
0             It’s good not bad I ate this  
1                        Awesome,delicious  
2   Average It was much better on that day  
3                                Delicious  
4                        Awesome,delicious

In [126]:
md.head()

Name  Recipe_Id  \
0             Raw Banana Fry          1   
1                    Payasam          2   
2            Soy Dal Paratha          3   
3         Aloo Palak Paratha          4   
4  Chettinad Chicken Biryani          5   

                                   Ingredients  Calories  \
0                                       Banana       400   
1      Vermicelli  jaggery   ghee  cocunutmilk       500   
2             Flour  soyachunks  ghee  mongdal       460   
3         Flour  ghee  potato  spinach  cheese       350   
4  Chicken  tomatoes  yogurt  tomatoes  onions       250   

                Food type Veg/nonveg  Rating  \
0                 Snacks        Veg      4.0   
1               Desserts        Veg      5.0   
2   Starters  MainCourse        Veg      3.0   
3   Starters  MainCourse        Veg      5.0   
4             MainCourse     Nonveg      5.0   

                                    Review  
0             It’s good not bad I ate this  
1                        Awesome,delicious  
2   Average It was much better on that day  
3                                Delicious  
4                        Awesome,delicious

In [127]:
md['Calories']=(lambda x:str(x))(md['Calories'])

In [128]:
md['Rating']=(lambda x:str(x))(md['Rating'])

In [129]:
md['tags']=md['Ingredients']+md['Food type']+md['Veg/nonveg']

In [130]:
new_df=md[['Name','Recipe_Id','tags']]

In [131]:
new_df

Name  Recipe_Id  \
0               Raw Banana Fry          1   
1                      Payasam          2   
2              Soy Dal Paratha          3   
3           Aloo Palak Paratha          4   
4    Chettinad Chicken Biryani          5   
5     AndhraStyleTomatoChutney          6   
6        Soya Chana Dal Bhurji          7   
7        Chicken Kothu Paratha          8   
8           Masoor Dal Kichidi          9   
9                 Banana Kheer         10   
10                Banana Appam         11   
11              Paneer Paratha         12   
12         Palak Paneer Lifafa         13   
13   Chicken Egg Parantha Roll         14   
14  Tangy Tamaring Prawn curry         15   
15    Andhra Style Guntur Idli         16   
16       Hyderabadi Veg Dalcha         17   
17         Phool Makhane Kheer         18   
18          Masala Tomato Upma         19   
19         Hyderabadi Dum Chai         20   
20       Butter Chicken Kulcha         21   
21        Paneer Butter Masala         22   
22        Butter Chicken curry         23   
23             Chana dal pulao         24   
24                  Keema Naan         25   
25                  Palak Vada         26   
26                Kadai Paneer         27   
27                Shahi Paneer         28   
28                Matar paneer         29   

                                                 tags  
0                                 Banana Snacks  Veg   
1   Vermicelli  jaggery   ghee  cocunutmilk Desser...  
2   Flour  soyachunks  ghee  mongdal Starters  Mai...  
3   Flour  ghee  potato  spinach  cheese Starters ...  
4   Chicken  tomatoes  yogurt  tomatoes  onions Ma...  
5                     Tomatoes  mustard Starters Veg   
6    Soya  onions  tomato  lemonjuice MainCourse Veg   
7   Paratha  chickencurry  shreddedchicken Starter...  
8      Masoordal  onion  tomato  rice MainCourse Veg   
9                 Banana  jaggery  nuts Desserts Veg   
10  Banana  riceflour  jaggery  coconut Breakfast ...  
11  Paneer  wheatflour  onion  ghee Starters  Main...  
12  Wheatflour  cornflour  paneer  spinach  ghee  ...  
13  Wheatflour  chicken  yogurt  lemonjuice  mayon...  
14         Prawns  onion  tomato   MainCourse Nonveg   
15  Idli  chanadal  uraddal  gunturchillies Breakf...  
16    Chanadal  onion  tomatoes  ghee MainCourse Veg   
17           Makhana  milk  ghee  sugar Desserts Veg   
18   Fuji  onion  tomato  carrot  ghee Breakfast Veg   
19             Tealeaves  milk Snacks  Breakfast Veg   
20   Kulchas  chicken  tomato  onion Starters Nonveg   
21  Paneer  butter  onions  tomato Starters  MainC...  
22  Chicken   butter  onion  tomato Starters  Main...  
23        Rice  chanadal  onion  tomato Starters Veg   
24      Mutton  maida  onion  chilli Starters Nonveg   
25  Spinach  greenchilli  chanadal  mangopowder Br...  
26  Paneer   capsicum  onion  redchilli MainCourse...  
27       Paneer  yogurt  nuts  cheese MainCourse Veg   
28   Greenpeas  paneer  cheese  onion MainCourse Veg

In [132]:
print(new_df['tags'][1])

Vermicelli  jaggery   ghee  cocunutmilk Desserts  Veg 


In [133]:
import nltk

In [134]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [135]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [136]:
new_df['tags']=new_df['tags'].apply(stem)

/var/folders/0v/ddjwkpz50kb5wq8lc5c05sdc0000gn/T/ipykernel_802/3514595201.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


In [137]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000,stop_words='english')

In [138]:
new_df['tags'][8]

'masoord onion tomato rice maincours veg'

In [139]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [140]:
vectors[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [141]:
vectors.shape

(29, 60)

In [142]:
cv.get_feature_names_out()

array(['banana', 'breakfast', 'butter', 'capsicum', 'carrot', 'chanad',
       'chees', 'chicken', 'chickencurri', 'chilli', 'coconut',
       'cocunutmilk', 'cornflour', 'dessert', 'egg', 'flour', 'fuji',
       'ghee', 'greenchilli', 'greenpea', 'gunturchilli', 'idli',
       'jaggeri', 'kulcha', 'lemonjuic', 'maida', 'maincours', 'makhana',
       'mangopowd', 'masoord', 'mayonnais', 'milk', 'mongdal', 'mustard',
       'mutton', 'nonveg', 'nut', 'onion', 'paneer', 'paratha', 'potato',
       'prawn', 'redchilli', 'rice', 'riceflour', 'shreddedchicken',
       'snack', 'soya', 'soyachunk', 'spinach', 'starter', 'sugar',
       'tealeav', 'tomato', 'tomatoketchup', 'uradd', 'veg', 'vermicelli',
       'wheatflour', 'yogurt'], dtype=object)

In [143]:
from sklearn.metrics.pairwise import cosine_similarity

In [144]:
similarity=cosine_similarity(vectors)

In [145]:
similarity.shape

(29, 29)

In [146]:
similarity[0]

array([1.        , 0.23570226, 0.21821789, 0.20412415, 0.        ,
       0.28867513, 0.23570226, 0.        , 0.23570226, 0.51639778,
       0.47140452, 0.21821789, 0.20412415, 0.18257419, 0.        ,
       0.23570226, 0.23570226, 0.23570226, 0.21821789, 0.51639778,
       0.        , 0.21821789, 0.        , 0.23570226, 0.        ,
       0.23570226, 0.23570226, 0.23570226, 0.23570226])

In [147]:
sorted(list(enumerate(similarity[8])),reverse=True,key=lambda x:x[1])[1:6]

[(6, 0.6666666666666669),
 (16, 0.6666666666666669),
 (23, 0.6666666666666669),
 (21, 0.6172133998483676),
 (14, 0.5477225575051662)]

In [148]:
def recommend(food):
    food_index=new_df[new_df['Name']==food].index[0]
    distances=similarity[food_index]
    food_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in food_list:
        print(new_df.iloc[i[0]].Name)
        print(new_df.iloc[i[0]].tags)

In [149]:
recommend('Soy Dal Paratha')

Aloo Palak Paratha
flour ghee potato spinach chees starter maincours veg
Paneer Paratha
paneer wheatflour onion ghee starter maincours veg
Hyderabadi Veg Dalcha
chanad onion tomato ghee maincours veg
Paneer Butter Masala
paneer butter onion tomato starter maincours veg
Palak Paneer Lifafa
wheatflour cornflour paneer spinach ghee onion starter veg


In [150]:
new_df.iloc[15].Name

'Andhra Style Guntur Idli'

In [151]:
new_df[new_df['Name']=='Banana Kheer'].index[0]

9